version: "3"
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /var/www/sword
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - .:/var/www/sword
      - ./storage/logs:/var/logs
    links:
      - db
    command: [ "npm","run", "start-${STAGE:-development}" ]
  db:
    image: mariadb:latest
    ports:
      - "33306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=sword
    volumes:
      - ./:/var/www/sword